"""
Summarization Agent module.
This module implements the summarization logic using OpenRouter and Chain of Density prompting.
"""

import logging
import re
import unicodedata
import uuid
from typing import Any

from langchain_core.messages import BaseMessage, HumanMessage
from langchain_openai import ChatOpenAI
from tenacity import Retrying, stop_after_attempt, wait_exponential

from domain_models.config import ProcessingConfig
from domain_models.constants import PROMPT_INJECTION_PATTERNS
from domain_models.manifest import SummaryNode
from matome.config import get_openrouter_api_key, get_openrouter_base_url
from matome.exceptions import SummarizationError
from matome.interfaces import PromptStrategy

logger = logging.getLogger(__name__)


class SummarizationAgent:
    """
    Agent responsible for summarizing text using an LLM.
    """

    def __init__(
        self,
        config: ProcessingConfig,
        strategy: PromptStrategy,
        llm: ChatOpenAI | None = None,
    ) -> None:
        """
        Initialize the SummarizationAgent.

        Args:
            config: Processing configuration containing model name, retries, etc.
            strategy: The prompt strategy to use for summarization.
            llm: Optional pre-configured LLM instance. If None, it will be initialized from config.
        """
        self.config = config
        self.strategy = strategy
        self.model_name = config.summarization_model

        # Determine API key and Base URL
        api_key = get_openrouter_api_key()
        base_url = get_openrouter_base_url()

        self.mock_mode = api_key == "mock"

        self.llm: ChatOpenAI | None = None

        if llm:
            self.llm = llm
        elif api_key and not self.mock_mode:
            self.llm = ChatOpenAI(
                model=self.model_name,
                api_key=api_key,
                base_url=base_url,
                temperature=config.llm_temperature,
                max_retries=config.max_retries,
            )
        else:
            self.llm = None

    def summarize(
        self, text: str | list[str], context: dict[str, Any] | None = None
    ) -> SummaryNode:
        """
        Summarize the provided text using the injected strategy.

        Args:
            text: The text to summarize. Can be a string or list of strings.
            context: Optional context containing metadata (e.g., node ID, level).

        Returns:
            The summary node generated by the model.
        """
        request_id = str(uuid.uuid4())

        # Process input text (for logging/validation, we join if list)
        text_str = "\n\n".join(text) if isinstance(text, list) else text

        if not text_str:
            logger.debug(f"[{request_id}] Skipping empty text summarization.")
            if context:
                return SummaryNode(text="", **context)
            return SummaryNode(
                id=str(uuid.uuid4()), text="", level=0, children_indices=[]
            )

        # Validate input for security
        self._validate_input(
            text_str, self.config.max_input_length, self.config.max_word_length
        )

        # Sanitize prompt injection
        if isinstance(text, list):
            safe_text: str | list[str] = [self._sanitize_prompt_injection(t) for t in text]
            # Use joined string for mock summary to be safe
            safe_text_str = "\n".join(safe_text)
        else:
            safe_text = self._sanitize_prompt_injection(text)
            safe_text_str = safe_text

        if self.mock_mode:
            return self._handle_mock_mode(safe_text_str, context, request_id)

        if not self.llm:
            msg = f"[{request_id}] LLM not initialized (missing API Key?). Cannot perform summarization."
            logger.error(msg)
            raise SummarizationError(msg)

        if self.config.summarization_model != self.model_name:
            logger.debug(
                f"[{request_id}] Config model {self.config.summarization_model} differs from agent model {self.model_name}. Using agent model."
            )

        try:
            prompt = self.strategy.format_prompt(safe_text, context)
            messages = [HumanMessage(content=prompt)]

            response = self._invoke_llm(messages, self.config, request_id)
            response_content = self._process_response(response, request_id)

            return self._create_summary_node(response_content, context)

        except Exception as e:
            logger.exception(
                f"[{request_id}] Summarization failed for text length {len(text_str)}"
            )
            msg = f"Summarization failed: {e}"
            raise SummarizationError(msg) from e

    def _handle_mock_mode(
        self, safe_text_str: str, context: dict[str, Any] | None, request_id: str
    ) -> SummaryNode:
        """Handle mock mode summarization."""
        logger.info(f"[{request_id}] Mock mode enabled. Returning static summary.")
        mock_summary = f"Summary of {safe_text_str[:20]}..."
        data: dict[str, Any] = {"text": mock_summary}
        if context:
            data.update(context)
        # Ensure required fields are present if not in context
        if "id" not in data:
            data["id"] = str(uuid.uuid4())
        if "level" not in data:
            data["level"] = 1
        if "children_indices" not in data:
            data["children_indices"] = []
        return SummaryNode(**data)

    def _create_summary_node(
        self, response_content: str, context: dict[str, Any] | None
    ) -> SummaryNode:
        """Parse LLM response and create SummaryNode."""
        parsed_data = self.strategy.parse_output(response_content)

        # Map 'summary' to 'text' if needed
        if "summary" in parsed_data and "text" not in parsed_data:
            parsed_data["text"] = parsed_data.pop("summary")

        # Merge context
        if context:
            parsed_data.update(context)

        return SummaryNode(**parsed_data)

    def _validate_input(
        self, text: str, max_input_length: int, max_word_length: int
    ) -> None:
        """
        Sanitize and validate input text.
        """
        # 0. Unicode Normalization (NFKC)
        normalized_text = unicodedata.normalize("NFKC", text)

        # 1. Length Check
        if len(normalized_text) > max_input_length:
            msg = f"Input text exceeds maximum allowed length ({max_input_length} characters)."
            raise ValueError(msg)

        # 2. Control Character Check (Unicode)
        # Allowed whitespace
        allowed_controls = {"\n", "\t", "\r"}

        for char in normalized_text:
            category = unicodedata.category(char)
            # Check for control categories: Cc (Control), Cf (Format), Co (Private Use), Cn (Not Assigned)
            # Cs (Surrogate) - Python strings usually don't have Cs if valid unicode, but good to check.
            # Emojis are typically So (Symbol, Other), which is fine.
            if category in ("Cc", "Cf", "Co", "Cn") and char not in allowed_controls:
                msg = f"Input text contains invalid control character: {char!r} (U+{ord(char):04X})"
                raise ValueError(msg)

        # 3. Tokenizer DoS Protection
        words = normalized_text.split()
        if not words:
            return

        longest_word_len = max((len(w) for w in words), default=0)
        if longest_word_len > max_word_length:
            msg = f"Input text contains extremely long words (>{max_word_length} chars) - potential DoS vector."
            raise ValueError(msg)

    def _sanitize_prompt_injection(self, text: str) -> str:
        """
        Basic mitigation for Prompt Injection using case folding.
        """
        # 1. Normalize text first (NFKC)
        normalized_text = unicodedata.normalize("NFKC", text)

        sanitized = normalized_text
        for pattern in PROMPT_INJECTION_PATTERNS:
            # We use re.sub for flexible matching with IGNORECASE which handles case folding.
            sanitized = re.sub(pattern, "[Filtered]", sanitized, flags=re.IGNORECASE)

        return sanitized

    def _invoke_llm(
        self, messages: list[HumanMessage], config: ProcessingConfig, request_id: str
    ) -> BaseMessage:
        """
        Invoke the LLM with exponential backoff retry logic.
        """
        if not self.llm:
            msg = "LLM not initialized"
            raise SummarizationError(msg)

        response = None
        for attempt in Retrying(
            stop=stop_after_attempt(config.max_retries),
            wait=wait_exponential(multiplier=1, min=2, max=10),
            reraise=True,
        ):
            with attempt:
                if attempt.retry_state.attempt_number > 1:
                    logger.warning(
                        f"[{request_id}] Retrying LLM call (Attempt {attempt.retry_state.attempt_number}/{config.max_retries})"
                    )

                if hasattr(self.llm, "invoke"):
                    response = self.llm.invoke(messages)
                else:
                    response = self.llm(messages)  # type: ignore[operator]

        if not response:
            msg = f"[{request_id}] No response received from LLM."
            raise SummarizationError(msg)

        return response

    def _process_response(self, response: BaseMessage, request_id: str) -> str:
        """
        Process and extract content from the LLM response.
        """
        content: str | list[str | dict[str, Any]] = response.content

        if isinstance(content, str):
            return content
        if isinstance(content, list):
            logger.warning(f"[{request_id}] Received list content from LLM: {content}")
            return " ".join([str(c) for c in content])

        logger.warning(
            f"[{request_id}] Received unexpected content type from LLM: {type(content)}"
        )
        return str(content)
