from typing import Protocol

from src.domain_models.document import EnrichedDocument, RaptorNode


class DocumentRepositoryProtocol(Protocol):
    def get_node_by_id(self, node_id: str) -> RaptorNode: ...
    def save_node(self, node: RaptorNode) -> None: ...
    def get_document_by_id(self, document_id: str) -> EnrichedDocument: ...
    def save_document(self, document: EnrichedDocument) -> None: ...
