from collections.abc import Iterable, Iterator
from typing import Protocol, runtime_checkable

from domain_models.config import ProcessingConfig
from domain_models.manifest import Chunk, Cluster


@runtime_checkable
class Chunker(Protocol):
    """
    Protocol for text chunking engines.

    Implementations are responsible for dividing large text documents into smaller,
    manageable segments (chunks) while preserving semantic meaning as much as possible.
    """

    def split_text(self, text: str | Iterable[str], config: ProcessingConfig) -> Iterator[Chunk]:
        """
        Split text into chunks.

        This method should handle normalization, sentence splitting, and merging based on
        the configuration provided (e.g., max_tokens).

        Args:
            text: The full input text or an iterable of text segments (for streaming).
                  If empty, should yield nothing.
            config: Configuration parameters including `max_tokens` and `overlap`.

        Returns:
            An iterator of `Chunk` objects, each containing the chunk text and metadata.
        """
        ...


@runtime_checkable
class Clusterer(Protocol):
    """
    Protocol for clustering engines.

    Implementations should group similar text chunks or nodes based on their vector embeddings
    to facilitate hierarchical summarization (RAPTOR).
    """

    def cluster_nodes(self, embeddings: list[list[float]], config: ProcessingConfig) -> list[Cluster]:
        """
        Cluster nodes based on embeddings.

        This method identifies groups of similar nodes to be summarized together.

        Args:
            embeddings: A list of vectors (list of floats), where each vector corresponds to a node.
                        The order of embeddings must match the order of nodes being clustered.
            config: Configuration parameters such as `n_clusters` or `clustering_algorithm`.

        Returns:
            A list of `Cluster` objects.
            Each `Cluster` contains `node_indices` which correspond to the indices of the
            input `embeddings` list.
        """
        ...


@runtime_checkable
class Summarizer(Protocol):
    """
    Protocol for summarization engines.

    Implementations should generate concise summaries of the provided text, respecting
    token limits and other configuration parameters.
    """

    def summarize(self, text: str, config: ProcessingConfig) -> str:
        """
        Summarize the provided text.

        Args:
            text: The text to summarize. If empty, behavior depends on implementation
                  (may return empty string or raise error).
            config: Configuration parameters such as `model_name` and `max_summary_tokens`.

        Returns:
            The summary text generated by the model.
        """
        ...
